server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 888888
    #    url: jdbc:mysql://localhost:3306/cby
    #    用来指定编码格式为utf8,指定亚洲上海的区时
    #    useSSL=false:通过账号密码连接，  ，true：通过证书或者令牌
    #    url: jdbc:mysql://localhost:3306/cby?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    url: jdbc:mysql://localhost:3306/ssm_example?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
pagehelper:
  helperDialect: mysql
  reasonable: true  #开启优化，如果开启优化，在分页页码结果没有数据的时候,会显示有数据的页码数据
  supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
  pageSizeZero: false #pageSize=0 返回所有
  params: count=countSql
mybatis:
  mapper-locations: mapper/*.xml
  map-underscore-to-camel-case : true
  type-aliases-package: com.example.api_project.pojo